---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: sqlite
          ini-values: include_path=.:/usr/share/php
      - name: Run tests
        run: |
          pear run-tests -d tests/
